services:
  ope:
    build:
      context: ope
    volumes:
      - ./pbf:/pbf

  postgres:
    image: postgis/postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./sql:/sql
      - ./pbf:/pbf
      - pgdata:/var/lib/postgresql/data
    # restart:

  time_machine:
    build:
      context: time_machine
    environment:
      - CONFIG=/srv/app/conf.yaml
    volumes:
      - ./time_machine:/srv/app
      - ./conf.yaml:/srv/app/conf.yaml
    depends_on:
      - postgres

volumes:
  pgdata:
